services:
  - type: web
    name: dealzy-server
    runtime: node
    plan: free
    branch: main
    autoDeployTrigger: commit
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
